# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a17802e8367addaaeed63e38932c79026a69cba01879003661477ccdbcb37746f3c1194189b8b9d0936b96cb113d9da5b3a5c1cea04b79392f0ca8859bf23007

test:
  secret_key_base: 75ef1b665040d9009cb7c216e93b8091efb9d6c1e33e9b802c28250124fee0314b4e935438ee6f322981b1025a8a4aaa994147b5d39ac0c527f51737c4d5e8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
